onvif:
  - mac: a2:a2:a2:a2:00:1b
    ports:
      server: 8107
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel27
    uuid: bd5931c5-92cd-46ac-8b9b-813d42becd3f
    highQuality:
      rtsp: /cam/realmonitor?channel=27&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=27&subtype=0
      width: 960
      height: 1080
      framerate: 15
      bitrate: 2048
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=27&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=27&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
