onvif:
  - mac: a2:a2:a2:a2:00:03
    ports:
      server: 8083
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel3
    uuid: b34b1827-1c48-4a6d-bc5d-3ec9ec07194f
    highQuality:
      rtsp: /cam/realmonitor?channel=3&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=3&subtype=0
      width: 960
      height: 576
      framerate: 25
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=3&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=3&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
