onvif:
  - mac: a2:a2:a2:a2:00:18
    ports:
      server: 8104
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel24
    uuid: 2376862d-00a7-4675-9b25-d16ee26655fe
    highQuality:
      rtsp: /cam/realmonitor?channel=24&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=24&subtype=0
      width: 960
      height: 1080
      framerate: 15
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=24&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=24&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
