onvif:
  - mac: a2:a2:a2:a2:00:19
    ports:
      server: 8105
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel25
    uuid: dfc169cf-52d9-4212-a1ef-3167d9c8188b
    highQuality:
      rtsp: /cam/realmonitor?channel=25&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=25&subtype=0
      width: 960
      height: 576
      framerate: 15
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=25&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=25&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
