onvif:
  - mac: a2:a2:a2:a2:00:08
    ports:
      server: 8088
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel8
    uuid: f8860e6a-fae0-468e-9198-6d94b93d962e
    highQuality:
      rtsp: /cam/realmonitor?channel=8&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=8&subtype=0
      width: 960
      height: 576
      framerate: 25
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=8&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=8&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
