onvif:
  - mac: a2:a2:a2:a2:00:09
    ports:
      server: 8089
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel9
    uuid: 458cbaa1-7683-43df-8ca5-a71fbce495f2
    highQuality:
      rtsp: /cam/realmonitor?channel=9&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=9&subtype=0
      width: 960
      height: 576
      framerate: 15
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=9&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=9&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
