onvif:
  - mac: a2:a2:a2:a2:00:1a
    ports:
      server: 8106
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel26
    uuid: 495cca48-6efd-435d-968b-bb7870b1a6bf
    highQuality:
      rtsp: /cam/realmonitor?channel=26&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=26&subtype=0
      width: 960
      height: 576
      framerate: 15
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=26&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=26&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
