onvif:
  - mac: a2:a2:a2:a2:00:14
    ports:
      server: 8100
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel20
    uuid: 5dd1cae4-b6f0-42f5-a58c-ebd90c747e79
    highQuality:
      rtsp: /cam/realmonitor?channel=20&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=20&subtype=0
      width: 960
      height: 576
      framerate: 15
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=20&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=20&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
