onvif:
  - mac: a2:a2:a2:a2:00:0f
    ports:
      server: 8095
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel15
    uuid: b5b05de8-269e-4b0e-b410-1d573d0ae4f9
    highQuality:
      rtsp: /cam/realmonitor?channel=15&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=15&subtype=0
      width: 960
      height: 1080
      framerate: 15
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=15&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=15&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
