onvif:
  - mac: a2:a2:a2:a2:00:1d
    ports:
      server: 8109
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel29
    uuid: 352a662b-5366-41ac-9aa8-e181a75cfc82
    highQuality:
      rtsp: /cam/realmonitor?channel=29&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=29&subtype=0
      width: 960
      height: 1080
      framerate: 15
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=29&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=29&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
