onvif:
  - mac: a2:a2:a2:a2:00:0d
    ports:
      server: 8093
      rtsp: 8554
      snapshot: 8580
    name: VideoSourceConfig_Channel13
    uuid: 73df754c-e7e1-4c55-958a-5ac80a9ebd11
    highQuality:
      rtsp: /cam/realmonitor?channel=13&subtype=0&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=13&subtype=0
      width: 960
      height: 576
      framerate: 25
      bitrate: 1024
      quality: 4
    lowQuality:
      rtsp: /cam/realmonitor?channel=13&subtype=1&unicast=true&proto=Onvif
      snapshot: /onvifsnapshot/media_service/snapshot?channel=13&subtype=1
      width: 352
      height: 288
      framerate: 7
      bitrate: 160
      quality: 1
    target:
      hostname: 192.168.6.201
      ports:
        rtsp: 554
        snapshot: 80
